### ISSUE TITLE
Upstream issues that require fixing

### ISSUE THREAD

**Issue by GwenNelson** [GarethNelson/yo#1]
This is more of a TODO list for my own personal use, noted here in public so progress can be observed

- [x] https://github.com/steemit/yo/issues/52 - import email templates
I am unable to import the templates mentioned for legal reasons - however, the current code does not correctly implement templates for each notification type, and that is something that I CAN fix

Commit here adds correctly formatted templates for vote+follow events https://github.com/GarethNelson/yo/commit/c93153750a08bea51b62e3644afdb4a87ba9e567

I will revisit this at a later date once all event types actually work (in current codebase, they do not)

- [x] https://github.com/steemit/yo/issues/111 - implement blockchain follower coordination
This can be done quite trivially, will require testing of multiple instances to ensure race conditions do not occur

Commit here implements this: https://github.com/GarethNelson/yo/commit/b59e602d299c74adf08558eed6a511fb5bca6bc4

Failover has been tested, requires more testing for edge cases

- [x] https://github.com/steemit/yo/issues/105 - Incorrect result counting in get_priority_count

Was caused originally by schema changes, now fixed but requires testing:
https://github.com/GarethNelson/yo/commit/9b3b88f55ceaae43afb52ed8eb7f4739e277dfe2

- [x] https://github.com/steemit/yo/issues/97 - Basic functionality: ensure each type of notification triggers transports

The "feed" event has no implementation at present and is probably not sane for MVP, so is being left out.
The "reward" event also has no implementation, but should be fairly trivial to implement

comment_reply vs post_reply needs more extensive testing

account_update needs to be split into different types of account_update and tested, sane templates for account_update need to be written

- [x] https://github.com/steemit/yo/issues/110 - Fix rate limits
Essentially fixed, but needs testing to ensure edge cases are also fixed:
https://github.com/GarethNelson/yo/commit/cd12f4eaf4dd4e27cefb930db1a6ef882b26c9b3

Stuff I can't legally do, or can only partly do for legal reasons

https://github.com/steemit/yo/issues/112 -  Add SMS message templates
As with email templates, I am unable to legally provide SMS templates that claim to be from Steemit Inc, but this can still be implemented

https://github.com/steemit/yo/issues/108 - request user's phone number from steemitapi
For legal reasons I am not able to implement this, but I can implement a mock module, and I can implement a python client for signed requests

https://github.com/steemit/yo/issues/109 - request user's email address from steemitapi
As above, I am not able to implement this for legal reasons, but I can implement a mock module

**Comment by GwenNelson** [comment]
The above issues are all as outlined here:
https://github.com/steemit/yo/issues/113

As can be seen, I have been fixing them one by one in this repo where legally possible to do so, but please note that these fixes can NOT be merged upstream without my consent, see the license file for details:
https://github.com/GarethNelson/yo/blob/master/LICENSE

**Comment by GwenNelson** [comment]
Note to steemit inc:

I am happy to license these changes under MIT immediately at a cost of $150 payable in SBD or paypal.

This offer is valid until I relicense my fork under GPLv2.
